#!/bin/bash
if [ -n "$1" ]
	then
		root_username=$1
	else
		echo "MongoDB root username required"
		return
fi

if [ -n "$2" ]
	then
		root_password=$2
	else
		echo "MongoDB root password required"
		return
fi

if [ -n "$3" ]
	then
		app_username=$3
	else
		echo "MongoDB application username required"
		return
fi

if [ -n "$4" ]
	then
		app_password=$4
	else
		echo "MongoDB application password required"
		return
fi

docker network create pipokernet

# The port is not published: only containers in pipokernet can reach the database
docker run -d \
	--network pipokernet \
	-v pipoker-mongodb-data:/data/db \
	-e MONGO_INITDB_ROOT_USERNAME=$root_username \
	-e MONGO_INITDB_ROOT_PASSWORD=$root_password \
	-e MONGO_INITDB_DATABASE=pipoker \
	-e MONGODB_APP_USERNAME=$app_username \
	-e MONGODB_APP_PASSWORD=$app_password \
	--name mongodb \
	pipoker/mongodb
